 version: 2
 jobs:
   build:
     docker:
       - image: amsharifian/muir-docker:1.0
     steps:
       - checkout
       - run: printf 'y\ny\ny\n' | ./scripts/muir-setup.sh
       - run: ./build.sh
