 version: 2
 jobs:
   build:
     docker:
       - image: amd64/ubuntu:18.04
     steps:
       - checkout
       - run: apt-get install sudo -y
       - run: printf 'y\ny\ny\n' | ./scripts/muir-setup.sh
